### ISSUE TITLE
Launch in CERN SWAN

### ISSUE THREAD

**Issue by lobis** [lobis/rest-for-physics-demo#1]
Hello @etejedor,

I am working on creating a standalone demo for [REST-for-Physics](https://github.com/rest-for-physics/framework). Currently this repository is launchable on [Binder](https://mybinder.org/v2/gh/lobis/rest-for-physics-demo/HEAD?labpath=demo.ipynb) for anyone to use, however, I am wondering if its possible to do the same on CERN SWAN.

Do you have any recommendation? If possible I would like to use the same approach, using containers.

Thanks!

**Comment by etejedor** [comment]
Hi,

The equivalent in SWAN would be to have a repo like this:

https://github.com/etejedor/distrdf-dimuon-analysis

Note how that has an "Open in SWAN" banner.

Users would find ROOT in SWAN, but if they need some extra packages for REST-for-Physics, they would need to install them in their CERNBox.

**Comment by lobis** [comment]
Thanks!
